
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
  #error:
  #  whitelabel:
   #   enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
    password:
    #url: jdbc:postgresql://ec2-52-70-186-184.compute-1.amazonaws.com:5432/d10tbg3k81g9bi
    #username: tppxxefmbngmfb
    #password: b8a1260a3c0e5533132bc03133f95f3bb6a89a579dab5751f15b0117affac688


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      #dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    jcache:
      config: classpath:ehcache.xml




  #mvc:
   # throw-exception-if-no-handler-found: true
  #resources:
   # add-mappings: false

