
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
    #error:
    #  whitelabel:
  #   enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
    password:

    #url: jdbc:postgresql://ec2-54-172-175-251.compute-1.amazonaws.com/d7gsmpbma7jor
    #username: aaetzyzfzzyfsp
    #password: 239b4d357f6ef2f1ea9815abae13926d8a762fde0a47898206e4a5a6d2b71bb1
    #data: classpath:/create.sql


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      #dialect: org.hibernate.dialect.MySQL8Dialect
      dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    jcache:
      config: classpath:ehcache.xml




    #mvc:
    # throw-exception-if-no-handler-found: true
    #resources:
    # add-mappings: false

